name: Java CI
on: push
jobs:
  clonedown:
    name: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
    - uses: actions/checkout@v2
  test:
    name: Test
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      run: ./ci/unit-test-app.sh
    needs: clonedown
  build:
    name: Build
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      run: ./ci/build-app.sh
      uses: actions/upload-artifact@v2
      with:
        name: code
        path: .
    needs: clonedown