name: Java CI
on: push
jobs:
  clonedown:
    name: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  test:
    name: Test
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Give permissions
        run: chmod +x ci/unit-test-app.sh
      - name: Test
        run: ./ci/unit-test-app.sh
    needs: clonedown
  build:
    name: Build
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Give permissions
        run: chmod +x ci/build-app.sh
      - name: Build-set
        run: ./ci/build-app.sh
    needs: clonedown