name: Java CI
on: push
jobs:
  clonedown:
    name: Clone-down
    runs-on: ubuntu-latest
    uses: actions/checkout@v2
  test:
    name: Test
    run: ./ci/unit-test-app.sh
    needs: clonedown
  build:
    name: Build
    container: gradle:6-jdk11
    run: ./ci/build-app.sh
    needs: clonedown
    uses: actions/upload-artifact@v2
    with:
      name: code
      path: .